/* Checksum.ai autogenerated test */
import { test as base, expect } from "@playwright/test";
import { init, IChecksumPage } from "@checksum-ai/runtime";

const { test, defineChecksumTest, login } = init(base);

test.describe("Expenses", () => {
  test.beforeEach(async ({ page }: { page: IChecksumPage }) => {
    await login(page);
  });

  test(
    defineChecksumTest("Navigate to expenses", "hVHWo"),
    async ({ page }) => {
      await page.goto("https://staging.myworkpay.com/", {
        waitUntil: "domcontentloaded",
      });
      await page
        .checksumSelector("QxV9o")
        .checksumAI(
          "Click on the 'Expenses' link in the navigation bar to navigate to the expenses section."
        )
        .getByRole("link", { name: "Expenses", exact: true })
        .click();
      await expect(page).toHaveURL(/\/expenses(\?.*)?(\#.*)?$/);
      await expect(
        page.getByText("Expenses settings", { exact: true })
      ).toBeVisible();
      await expect(
        page.getByText("Expense Account", { exact: true })
      ).toBeVisible();
      await expect(page.getByText("Not Paid", { exact: true })).toBeVisible();
      await expect(page.getByText("Donations", { exact: true })).toBeVisible();
    }
  );
});
