/* Checksum.ai autogenerated test */
import { test as base, expect } from "@playwright/test";
import { init, IChecksumPage } from "@checksum-ai/runtime";

const { test, defineChecksumTest, login } = init(base);

test.describe("Expenses", () => {
  test.beforeEach(async ({ page }: { page: IChecksumPage }) => {
    await login(page);
  });

  test(
    defineChecksumTest(
      "Calculate the remaining leave balances before and after applying for leave",
      "jZYET"
    ),
    async ({ page }: { page: IChecksumPage }) => {
      await page.goto("/", { waitUntil: "domcontentloaded" });
      await page
        .checksumSelector("NTSZt")
        .checksumAI("Click on Leave to view options")
        .locator("div")
        .filter({ hasText: /^Leave$/ })
        .nth(2)
        .click();
      await page
        .checksumSelector("lMrkr")
        .checksumAI("Click on leave Balance to navigate to page")
        .getByRole("link", { name: "Leave Balance" })
        .click();
      await expect(page).toHaveURL(
        "https://staging.myworkpay.com/remote/leaves/leave_balances"
      );
      await expect(
        page.getByText("Leave Balances", { exact: true })
      ).toBeVisible();
      await expect(page.getByText("MC", { exact: true })).toBeVisible();
      await expect(page.getByText("JK", { exact: true })).toBeVisible();
      await page
        .checksumSelector("HijwT")
        .checksumAI("Click on Filter oPTIONS TO VIEW FILTERS FOR BALANCE")
        .getByRole("button", { name: "Filter by" })
        .click();
      await page
        .checksumSelector("cFZQb")
        .checksumAI("Click on Countries")
        .getByRole("button", { name: "Countries" })
        .click();
      await expect(page.getByText("Botswana", { exact: true })).toBeVisible();
      await expect(page.getByText("Ghana", { exact: true })).toBeVisible();
      await page
        .checksumSelector("4FHQD")
        .checksumAI("Click on Ghana checkbox to filter out values")
        .locator("label")
        .filter({ hasText: "Ghana" })
        .click();
      await expect(page.getByText("ghana", { exact: true })).toBeVisible();
      await expect(page.getByText("JK", { exact: true })).not.toBeVisible();
      await expect(page.getByText("LS", { exact: true })).not.toBeVisible();
      await expect(page.getByText("MC", { exact: true })).toBeVisible();
      await page
        .checksumSelector("xBrw9")
        .checksumAI("Click on x icon to close modal")
        .getByLabel("Close")
        .click();
      await page
        .checksumSelector("MKhZx")
        .checksumAI("Click on Leave Requests")
        .getByRole("link", { name: "Leave Requests" })
        .click();
      await expect(
        page.getByText("Leave Balances", { exact: true })
      ).not.toBeVisible();
      await expect(page.getByText("1", { exact: true })).not.toBeVisible();
      await expect(page).toHaveURL(/\/leaves(\?.*)?(\#.*)?$/);
      await expect(
        page.getByText("Leave requests", { exact: true })
      ).toBeVisible();
      await expect(
        page.getByText("Leave settings", { exact: true })
      ).toBeVisible();
      await page
        .checksumSelector("kMtek")
        .checksumAI("Click on downarrow to view Country Options")
        .locator(".css-1wy0on6 > div")
        .first()
        .click();
      await expect(page.getByText("Ghana", { exact: true })).toBeVisible();
      await expect(page.getByText("Kenya", { exact: true })).toBeVisible();
      await page
        .checksumSelector("b8EK9")
        .checksumAI("Click on Ghana as the country option")
        .getByText("Ghana")
        .click();
      await expect(
        page.getByText("Botswana", { exact: true })
      ).not.toBeVisible();
      await expect(page.getByText("Kenya", { exact: true })).not.toBeVisible();
      await expect(page).toHaveURL(/\/leaves(\?.*)?(\#.*)?$/);
      await expect(page.getByText("PK", { exact: true })).toBeVisible();
      await page
        .checksumSelector("8c2cr")
        .checksumAI("Click on Issue Leave")
        .getByRole("button", { name: "Issue Leave" })
        .click();
      await expect(
        page.getByText("Select Country", { exact: true })
      ).toBeVisible();
      await expect(
        page.getByText("Select policy", { exact: true })
      ).toBeVisible();
      await page
        .checksumSelector("SQonl")
        .checksumAI("Click on down arrow next to country")
        .locator("#issue-leave-form > div > div > div > .css-1wy0on6 > div")
        .first()
        .click();
      await expect(page.getByText("Botswana", { exact: true })).toBeVisible();
      await expect(page.getByText("Kenya", { exact: true })).toBeVisible();
      await page
        .checksumSelector("sHbKv")
        .checksumAI("Click on Ghana")
        .getByLabel("Issue Leave")
        .getByText("Ghana")
        .click();
      await expect(
        page.getByText("Botswana", { exact: true })
      ).not.toBeVisible();
      await expect(page.getByText("Kenya", { exact: true })).not.toBeVisible();
      await expect(
        page.getByText("Select Country", { exact: true })
      ).not.toBeVisible();
      await page
        .checksumSelector("yGPDW")
        .checksumAI(" Click on down arrow next to Employees ")
        .locator(
          "#issue-leave-form > div:nth-child(2) > div > div > .css-1wy0on6 > div"
        )
        .click();
      await expect(page.getByText("KS", { exact: true })).toBeVisible();
      await expect(page.getByText("DL", { exact: true })).toBeVisible();
      await page
        .checksumSelector("D6Gef")
        .checksumAI("Click on Victor as Employee Option")
        .locator("div")
        .filter({ hasText: /^VWVictor Waichigo Kamauauto002General$/ })
        .first()
        .click();
      await expect(page.getByText("KS", { exact: true })).not.toBeVisible();
      await expect(page.getByText("DL", { exact: true })).not.toBeVisible();
      await page
        .checksumSelector("g33dZ")
        .checksumAI("Click on down arrow next to POLICY")
        .locator("div:nth-child(3) > div > div > .css-1wy0on6 > div")
        .click();
      await expect(page.getByText("Sick Leave", { exact: true })).toBeVisible();
      await expect(
        page.getByText("Paternity Leave", { exact: true })
      ).toBeVisible();
      await page
        .checksumSelector("NeNjn")
        .checksumAI("Click on Annual Leave")
        .getByLabel("Issue Leave")
        .getByText("Annual Leave")
        .nth(1)
        .click();
      await expect(
        page.getByText("Sick Leave", { exact: true })
      ).not.toBeVisible();
      await expect(
        page.getByText("Paternity Leave", { exact: true })
      ).not.toBeVisible();
      await expect(
        page.getByText("Select policy", { exact: true })
      ).not.toBeVisible();
      await page
        .checksumSelector("6RrhB")
        .checksumAI("Click on Start Date to view calendar options")
        .locator('button[name="from"]')
        .click();
      await expect(page.getByText("February", { exact: true })).toBeVisible();
      await expect(page.getByText("2024", { exact: true })).toBeVisible();
      await page
        .checksumSelector("IHbP3")
        .checksumAI("Click on 26 as option")
        .getByLabel("Choose Monday, February 26th, 2024")
        .click();
      await expect(
        page.getByText("February", { exact: true })
      ).not.toBeVisible();
      await expect(page.getByText("2024", { exact: true })).not.toBeVisible();
      await page
        .checksumSelector("Ld9Bp")
        .checksumAI("Click on Return Date to view Calendar options")
        .getByRole("button", { name: "Select date" })
        .click();
      await expect(page.getByText("February", { exact: true })).toBeVisible();
      await expect(page.getByText("2024", { exact: true })).toBeVisible();
      await page
        .checksumSelector("LWMiI")
        .checksumAI("Click on 1 as option")
        .getByLabel("Choose Friday, March 1st, 2024")
        .click();
      await expect(
        page.getByText("February", { exact: true })
      ).not.toBeVisible();
      await expect(page.getByText("2024", { exact: true })).not.toBeVisible();
      await page
        .checksumSelector("A8LNe")
        .checksumAI("Click on down arrow next to Reliever")
        .locator("div:nth-child(7) > div > div > .css-1wy0on6 > div")
        .click();
      await expect(page.getByText("KS", { exact: true })).toBeVisible();
      await expect(page.getByText("DL", { exact: true })).toBeVisible();
      await page
        .checksumSelector("7yD1C")
        .checksumAI("Click on Alicia to select person as Reliever")
        .locator("div")
        .filter({ hasText: /^ACAlisia CoutureQSC490General$/ })
        .first()
        .click();
      await expect(page.getByText("KS", { exact: true })).not.toBeVisible();
      await expect(page.getByText("DL", { exact: true })).not.toBeVisible();
      await expect(
        page.getByText("Search employees", { exact: true })
      ).not.toBeVisible();
      await page
        .checksumSelector("J36a8")
        .checksumAI("Fill Reason with example-reason-for-test")
        .getByPlaceholder("Reason...")
        .fill("example-reason-for-test");
      await page
        .checksumSelector("mK0il")
        .checksumAI("Click on Submit Button to submit record of issue leave")
        .getByRole("button", { name: "Submit" })
        .click();
      await page
        .checksumSelector("FDwBd")
        .checksumAI("Hover over submit button ")
        .getByRole("button", { name: "Loading... Submitting..." })
        .hover();
      await page
        .checksumSelector("yfqWM")
        .checksumAI("click on x button to close modal")
        .getByLabel("Close")
        .click();
      await page
        .checksumSelector("wl274")
        .checksumAI("Click on Leave Balance to view changes")
        .getByRole("link", { name: "Leave Balance" })
        .click();
      await expect(
        page.getByText("Leave Balances", { exact: true })
      ).toBeVisible();
      await expect(page.getByText("ghana", { exact: true })).toBeVisible();
      await expect(
        page.getByText("Leave requests", { exact: true })
      ).not.toBeVisible();
      await expect(
        page.getByText("Leave settings", { exact: true })
      ).not.toBeVisible();
      await expect(page).toHaveURL(
        "https://staging.myworkpay.com/remote/leaves/leave_balances"
      );
      await expect(page.getByText("MC", { exact: true })).toBeVisible();
    }
  );
});
